# Site settings
title: Hyojoy's line
description: 'Study blog' # write a nice description for your blog
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://hyodongnim.github.io/' # the base hostname & protocol for your site http://www.example.com
# google_analytics: 'UA-XXXXXX-X'
twitter_username: null

# Build settings
markdown: kramdown

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10

...
...
...

# --- Navigation bar options --- #

# List of links in the navigation bar

navbar-links:
  Category:
    - Paper: "/category/Paper"
    - Study: "/category/Study"

...
...
...
